### ISSUE TITLE
Nice work :). Question about integration?

### ISSUE THREAD

**Issue by asystentka-jolka** [dgtal1/extalife_custom_component#17]
Hi @dgtal1 

This is really nice work  :1st_place_medal: 
**Congratulation from AI-Speaker team :)** 

If you agree, we would like to add your integration to our product AI-Speaker as a officially delivered out of the box and supported by us.

There is one issue to do this now. 
We have the same licence as Home Assistant -> Apache License 2.0

![image](https://user-images.githubusercontent.com/43966761/84631685-15d5bd00-aeee-11ea-86af-9c9982c675de.png)

This licence is simillar to GPL 3.0 licence
![image](https://user-images.githubusercontent.com/43966761/84631751-330a8b80-aeee-11ea-8fe9-8f38618ae8b6.png)

Could you please consider the possibility to change the licence to Apache License 2.0 and allow us to add your integration to the AI-Speaker software?
(without this licence change and without your permission, we will not be able to push this  to HA in any time and we will not be able to add this code as "internal integration" / "out of the box integration")

Waiting for you response. Have a nice day!

**Comment by dgtal1** [comment]
Hello @asystentka-jolka !
Acknowledged🙂 I'm currently on holidays. I'll have a look at it when I come back

**Comment by asystentka-jolka** [comment]
Have a great vacation time!  :sunny: :surfer: :tropical_drink: :sunglasses::ice_cream:

**Comment by dgtal1** [comment]
Hi @asystentka-jolka !
I had a look and decided to change the license to Apache. I've changed it already in the repo, so now you guys should be fine to include it in your product. As long as it's open source (and I think it is) I'm fine with that.
Well, having this piece of software included in official HA release at some point in time would be great and it shouldn't be too difficult as I think the integration meets many of the requirements already.
