### ISSUE TITLE
Using the ExtaLifeAPI class outside the HA custom component

### ISSUE THREAD

**Issue by adamslodki** [dgtal1/extalife_custom_component#39]
I'm try using  ExtaLifeAPI to communicate with EFC-01 outside HA custom component

My code looks like this:

```
import asyncio
from pyextalife import ExtaLifeAPI

async def main():
    user = 'root'
    password = 'toor'
    host = '192.168.69.96'

    loop = asyncio.new_event_loop()

    controller = ExtaLifeAPI(loop, on_connect_callback=on_connect_handler, on_disconnect_callback=on_disconnect_handler)

    await controller.async_connect(user, password, host=host)

    controller_name = await controller.async_get_name()
    print (controller_name)

def on_connect_handler():
    print("Connected to controller")

def on_disconnect_handler():
    print("Disconnected from controller")

if __name__ == '__main__':
    asyncio.run(main())
```

but, i'm return error:

> Traceback (most recent call last):
  File "/home/adam/Desktop/extalife_custom_component/extalife/extalife_custom.py", line 25, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/adam/Desktop/extalife_custom_component/extalife/extalife_custom.py", line 13, in main
    await controller.async_connect(user, password, host=host)
  File "/home/adam/Desktop/extalife_custom_component/extalife/pyextalife.py", line 358, in async_connect
    await self._connection.async_connect()
  File "/home/adam/Desktop/extalife_custom_component/extalife/pyextalife.py", line 928, in async_connect
    await asyncio.wait_for(coro, 30.0)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
RuntimeError: Task <Task pending name='Task-2' coro=<BaseSelectorEventLoop.sock_connect() running at /usr/lib/python3.10/asyncio/selector_events.py:501> cb=[_release_waiter(<Future pendi...ask_wakeup()]>)() at /usr/lib/python3.10/asyncio/tasks.py:387]> got Future <Future pending cb=[BaseSelectorEventLoop._sock_write_done(9, handle=<Handle BaseS....96', 20400))>)()]> attached to a different loop

I'm don't understand loop parameter in ExtaLifeAPI __init__ method

It is possible to create simple documentation for the ExtaLifeAPI class to use it outside the HA component? Maybe as a separate git repository?

**Comment by gadulowaty** [comment]
ExtalifeAPI is based on asyncio library. if you want to use it with own program, then you should provide valid loop for ExtalifeAPI.
Please change in your example line:

loop = asyncio.new_event_loop()

to

loop = asyncio.get_running_loop()
 
For question about moving it to external repository - at this stage it is not ready, IMHO this is still very early alpha :)

**Comment by adamslodki** [comment]
Thank's, it works for me.
